config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :restaurants


  root to: "restaurants#home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]

has_many :reviews, dependent: :destroy

validates :phone_number, presence: true

validates :name, presence: true
validates :address, presence: true
# validates :category, presence: true

validates :category, inclusion: { in: CATEGORIES}

end

app/models/review.rb
class Review < ApplicationRecord

    # RATES = (0..5)

    belongs_to :restaurant

    validates :content, presence: true
    # validates :rating, presence: true

    # validates :rating, inclusion: { in: RATES }

    validates :rating, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }

    validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

    def index 
        @restaurants = Restaurant.all
    end

    def show
        @restaurant = Restaurant.find(params[:id])
    end

    def create
        
        @restaurant = Restaurant.new(restaurants_params)
        @restaurant.save 
        redirect_to restaurants_path
    
    end

    def new
        @restaurant = Restaurant.new
    end


    def home

    end
    
    def update 
        
        @restaurant = Restaurant.find(params[:id])
        @restaurant.update(restaurant_params)
        redirect_to restaurants_path(@restaurant)
    end


    private 
    def restaurants_params
        params.require(:restaurant).permit(:name, :address, :phone_number, :category)
    end 


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/home.html.erb
<img src="https://st.depositphotos.com/1147458/1222/i/600/depositphotos_12224003-stock-photo-beautiful-ruby-gems.jpg" width="200px">WELCOME HOME PAGE

app/views/restaurants/index.html.erb
OK JE SUIS DANS L'ACTION INDEX

<% @restaurants.each do |r| %>
<li>
<%= r.name %> 
<%# <button>edit</button>  %>
<%= link_to "edit", restaurant_path(r.id), :method => :get %>
<%# <%= button_to "edit", restaurant_path %>
</li>


<% end %>

<button>
<%= link_to "add", new_restaurant_path %>
</button>

app/views/restaurants/new.html.erb
CREE UN NOUVEAU RESTO STP

<%= simple_form_for @restaurant do |f| %>

<%= f.input :name %>
<%= f.input :address %>
<%= f.input :phone_number %>
<%= f.input :category %>
<%= f.submit "AJOUTER" %>
    
<% end %>

app/views/restaurants/show.html.erb
SHOW


<%= @restaurant.name %>


<%= simple_form_for @restaurant do |f| %>

<%= f.input :name %>
<%= f.input :address %>
<%= f.input :phone_number %>
<%= f.input :category %>
<%= f.submit "edit" %>
    
<% end %>